apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-backend
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-backend
  template:
    metadata:
      labels:
        app: voting-backend
    spec:
      containers:
      - name: backend
        image: voting-backend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: voting-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: voting-backend