apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-frontend
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-frontend
  template:
    metadata:
      labels:
        app: voting-frontend
    spec:
      containers:
      - name: frontend
        image: voting-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: voting-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: voting-frontend